name: Primer pipeline

# Cuando se va a ejecutar
on: 
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

# Ahora, qué queremos ejecutar; tenemos que construir los trabajos
jobs: 
  build: 
    runs-on: ubuntu-latest
    # En qué sistema van a trabajar; en esta caso última versión de ubuntu-osea en linux 
    steps:
      # pasos que se realizarán cuando se ejecute el pipeline 
      - name: Checkout repository
        uses: actions/checkout@v2 # Actualizado a v2

      - name: Análisis del proyecto
        run: echo Análisis del proyecto

      - name: Ejecución de un comando
        run: echo Está ejecutando el pipeline

      - name: Ejecución de varios comandos
        run: |
          echo Varias líneas
          ls -la
          # Nos muestra todos los archivos que hay
